<a href="https://colab.research.google.com/github/Shakib-4236/Artificial-Intelligence_Basic-Python/blob/main/Artificial_Intelligence_Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
arr = numpy.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [ ]:
import numpy as np
arr = np.array([11, 22, 33, 34, 85])
print(arr)

[11 22 33 34 85]


In [ ]:
import numpy as np
print(np.__version__)

1.22.4


In [ ]:
import numpy as np
arr = np.array([20, 30, 44, 77, 100])
print(arr)
print(type(arr))

[ 20  30  44  77 100]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr = np.array(66)
print(arr)

66


In [ ]:
import numpy as np
arr = np.array([[2, 4, 6], [10, 20, 30]])
print(arr)

[[ 2  4  6]
 [10 20 30]]


In [ ]:
import numpy as np
arr = np.array(10)
print(arr)

10


In [ ]:
import numpy as np
arr = np.array([[[[10, 20, 30], [50, 60, 70]], [[55, 88, 99], [77, 87, 95]]]])
print(arr)

[[[[10 20 30]
   [50 60 70]]

  [[55 88 99]
   [77 87 95]]]]


In [ ]:
import numpy as np
A = np.array(100)
B = np.array([11, 22, 33, 44, 55, 88])
C = np.array([[10, 20, 30], [70, 80, 90]])
D = np.array([[[2, 4, 6], [8, 10, 12]], [[14, 16, 20], [22, 24, 30]]])
print(A.ndim)
print(B.ndim)
print(C.ndim)
print(D.ndim)

0
1
2
3


In [ ]:
import numpy as np
#A = np.array(100)
#B = np.array([11, 22, 33, 44, 55, 88])
#C = np.array([[10, 20, 30], [70, 80, 90]])
D = np.array([[[2, 4, 6], [8, 10, 12]], [[14, 16, 20], [22, 24, 30]]])
'''print(A.ndim)
print(B.ndim)
print(C.ndim)
print(D.ndim)'''
print(D)

[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 20]
  [22 24 30]]]


In [ ]:
import numpy as np
arr = np.array([74, 38, 89, 72], ndmin=5)
print(arr)
print("number of dimensions : ", arr.ndim)

[[[[[74 38 89 72]]]]]
number of dimensions :  5


In [ ]:
import numpy as np
arr = np.array([17, 27, 31, 45])
print(arr[2])


31


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:5])


[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-4:-2])

[4 5]
