<a href="https://colab.research.google.com/github/Shakib-4236/Artificial-Intelligence_Basic-Python/blob/main/Artificial_Intelligence_Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
arr = numpy.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [ ]:
import numpy as np
arr = np.array([11, 22, 33, 34, 85])
print(arr)

[11 22 33 34 85]


In [ ]:
import numpy as np
print(np.__version__)

1.22.4


In [ ]:
import numpy as np
arr = np.array([20, 30, 44, 77, 100])
print(arr)
print(type(arr))

[ 20  30  44  77 100]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr = np.array(66)
print(arr)

66


In [ ]:
import numpy as np
arr = np.array([[2, 4, 6], [10, 20, 30]])
print(arr)

[[ 2  4  6]
 [10 20 30]]


In [ ]:
import numpy as np
arr = np.array(10)
print(arr)

10


In [ ]:
import numpy as np
arr = np.array([[[[10, 20, 30], [50, 60, 70]], [[55, 88, 99], [77, 87, 95]]]])
print(arr)

[[[[10 20 30]
   [50 60 70]]

  [[55 88 99]
   [77 87 95]]]]


In [ ]:
import numpy as np
A = np.array(100)
B = np.array([11, 22, 33, 44, 55, 88])
C = np.array([[10, 20, 30], [70, 80, 90]])
D = np.array([[[2, 4, 6], [8, 10, 12]], [[14, 16, 20], [22, 24, 30]]])
print(A.ndim)
print(B.ndim)
print(C.ndim)
print(D.ndim)

0
1
2
3


In [ ]:
import numpy as np
#A = np.array(100)
#B = np.array([11, 22, 33, 44, 55, 88])
#C = np.array([[10, 20, 30], [70, 80, 90]])
D = np.array([[[2, 4, 6], [8, 10, 12]], [[14, 16, 20], [22, 24, 30]]])
'''print(A.ndim)
print(B.ndim)
print(C.ndim)
print(D.ndim)'''
print(D)

[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 20]
  [22 24 30]]]


In [ ]:
import numpy as np
arr = np.array([74, 38, 89, 72], ndmin=5)
print(arr)
print("number of dimensions : ", arr.ndim)

[[[[[74 38 89 72]]]]]
number of dimensions :  5


In [ ]:
import numpy as np
arr = np.array([17, 27, 31, 45])
print(arr[2])


31


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:5])


[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-4:-2])

[4 5]


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:4:3])


[2]


In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,])
print(arr[::3])

[ 1  4  7 10]


In [12]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [13]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr.dtype)


int64


In [15]:
import numpy as np
arr = np.array([11, 22, 33, 44, 55])
x = arr.copy()
arr[0] = 100
print(arr)
print(x)


[100  22  33  44  55]
[11 22 33 44 55]


In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5 6 7 8]


In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5], ndmin=8)
print(arr)
print('shape of array :', arr.shape)


[[[[[[[[1 2 3 4 5]]]]]]]]
shape of array : (1, 1, 1, 1, 1, 1, 1, 5)


In [18]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [21]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 5, 7,8]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
5
7
8


In [23]:
import numpy as np
arr_1 = np.array([[1, 2], [3, 4]])
arr_2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr_1, arr_2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [24]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [25]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [26]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [27]:
import numpy as np
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [28]:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
